version: '3'

env:
  ROOT_DIR: '{{.ROOT_DIR}}'

tasks:
  copy:
    dir: '{{.ROOT_DIR}}'
    env:
      TASK_CWD: '{{.cwd}}'
    cmds:
      - composer run:task -q -- copy {{q .src}} {{q .dest}} {{if .ignore}}{{.ignore}}{{end}}
    requires:
      vars: [src, dest]
    internal: true

  placeholder:
    dir: '{{.ROOT_DIR}}'
    env:
      TASK_CWD: '{{.cwd}}'
    cmds:
      - composer run:task -q -- placeholder {{q .src}} {{q (toRawJson .replace)}} {{if .ignore}}{{.ignore}}{{end}}
    requires:
      vars: [src, replace]
    internal: true

  zip:
    dir: '{{.ROOT_DIR}}'
    env:
      TASK_CWD: '{{.cwd}}'
    cmds:
      - composer run:task -q -- zip {{q .src}} {{q .dest}} {{if .ignore}}{{.ignore}}{{end}}
    requires:
      vars: [src, dest]
    internal: true
